export const ACCOUNTANTS = {
  first_last_name: "Ortiz",
  middle_name: "Manuel",
  second_last_name: "Maldonado",
  company: "JW ACCOUNTING TAX SERVICE",
  phone: "787-390-9740",
  country: "53",
  name: "Jose",
  email: "jwtaxes@yahoo.com",
  state: "PR",
  zip_code: "00720",
  identidad_ssa: "P000445998",
  identidad_bso: "4658DR5R",
  identidad_efile: "0000000",
  address: "PO BOX 411",
  employer_insurance_number: "Prueba",
};
