export const ACCOUNTANTS = {
  first_last_name: "",
  middle_name: "",
  second_last_name: "",
  company: "",
  phone: "",
  country: "",
  name: "",
  email: "",
  state: "",
  zip_code: "",
  identidad_ssa: "",
  identidad_bso: "",
  identidad_efile: "",
  address: "",
  employer_insurance_number: "",
};
