export const EMPLOYER_DATA = {
  name: "Prueba",
  last_name: "Prueba",
  mother_last_name: "Prueba",
  first_name: "Prueba",
  middle_name: "Prueba",
  employee_type: "1",
  social_security_number: "2323",
  marital_status: "1",
  address: "Prueba",
  marbete: "23",
  type: 1,
  date_marb: null,
  clipboard: "23",
  exec_personal: 1,
  choferil: "23",
  regular_time: "23",
  period_norma: "1",
  licence: "23",
  category_cfse: "23",
  gender: 1,
  birthday: null,
  date_admission: null,
  date_egress: null,
  about_time: "23",
  mealtime: "23",
  vacation_hours: "23",
  vacation_date: null,
  number_dependents: "23",
  shared_custody: "23",
  number_concessions: "23",
  veteran: "23",
  type_payroll: 1,
  schedule_type: 1,
  payment_percentage: "23",
  address_state: "Prueba",
  address_country: "2",
  address_number: "Prueba",
  phone_number: "Prueba",
  smartphone_number: "Prueba",
};

export interface EMPLOYEER {
  name: string;
  last_name: string;
  mother_last_name: string;
  first_name: string;
  middle_name: string;
  employee_type: string;
  social_security_number: string;
  marital_status: string;
  address: string;
  marbete: string;
  type: number;
  date_marb: string;
  clipboard: string;
  exec_personal: number;
  choferil: string;
  regular_time: string;
  period_norma: string;
  licence: string;
  category_cfse: string;
  gender: number;
  birthday: string;
  date_admission: string;
  date_egress: string;
  about_time: string;
  mealtime: string;
  vacation_hours: string;
  vacation_date: string;
  number_dependents: string;
  shared_custody: string;
  number_concessions: string;
  veteran: string;
  type_payroll: number;
  schedule_type: number;
  payment_percentage: string;
  address_state: string;
  address_country: string;
  address_number: string;
  phone_number: string;
  smartphone_number: string;
}
